sudo: required
addons:
  firefox: "45.0"
language: ruby
rvm:
 - 2.3.0
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails db:seed RAILS_ENV=test
  - bundle exec rspec spec/
